### ISSUE TITLE
Doesn't appear to run on build?

### ISSUE THREAD

**Issue by jakewhiteley** [vshepel/vite-svg-sprite-wrapper#1]
The sprite.svg is only generated when an svg changes while the vite server is active: running `vite build` will not generate the sprite.

Similarly,  running `vite` without making a change to the svgs will also not generate the sprite - only when I add/amend an svg to the defined `icons` folder.

Is this intended behaviour?

**Comment by jakewhiteley** [comment]
@vshepel bumping the above

**Comment by 13twelve** [comment]
@jakewhiteley @kimchristiansen @vshepel I've made a PR that hopefully fixes this - https://github.com/vshepel/vite-svg-sprite-wrapper/pull/2

Something I couldn't figure out was how to add the generated sprite to the `manifest.json` - which I think would be a nice to have.

**Comment by jakewhiteley** [comment]
It apears this repo is abandoned by @vshepel.

I guess we should start a fork :)

**Comment by 13twelve** [comment]
@jakewhiteley I've sent @vshepel an email to see how we can help. Although he seems to still be active on GitHub, I'm conscious that his geographic location is set to Kyiv in the Ukraine and so his attentions might be spread a little.

**Comment by vshepel** [comment]
Strange that I haven't received notifications of new issues, I'll look today or tomorrow pr and add it. Thanks!
