### ISSUE TITLE
`outputDir` to `dist/`

### ISSUE THREAD

**Issue by mrleblanc101** [vshepel/vite-svg-sprite-wrapper#10]
How can I output the sprite in the `dist/` folder ?
The default `outputDir` is in the source folder which is very strange, I don't want to commit the sprite, only the originals.
So I changed the `outputDir` to `dist/`, but it doesn't seem to work.
I suspect this run and create the file, but then Vite overwrite the folder ?

**Comment by vshepel** [comment]
@mrleblanc101 Hi, can you send me your full configuration?

**Comment by mrleblanc101** [comment]
@vshepel 
```
import { defineConfig } from 'vite'
import vituum from 'vituum'
import twig from '@vituum/vite-plugin-twig'
import postcss from '@vituum/vite-plugin-postcss'
import ViteSvgSpriteWrapper from 'vite-svg-sprite-wrapper';

import customFunctions from './utils/twig.customFunctions.js';

export default defineConfig({
    build: {
        rollupOptions: {
            input: [
                './src/templates/emails/*.{json,latte,twig,liquid,njk,hbs,pug,html}',
                './src/templates/pages/**/*.{json,latte,twig,liquid,njk,hbs,pug,html}',
                '!./src/templates/pages/**/*.{latte,twig,liquid,njk,hbs,pug,html}.json'
            ]
        }
    },
    plugins: [
        vituum({
            imports: {
                filenamePattern: {
                    '+.css': [],
                    '+.scss': 'src/styles'
                }
            },

        }),
        postcss(),
        twig({
            root: './src/templates',
            dir: './src/templates/pages',
            base: './src/templates',
            functions: customFunctions,
        }),
        ViteSvgSpriteWrapper({
            icons: './src/svg/originals/**/*.svg',
            outputDir: './src/svg'
        })
    ]
});
```

**Comment by vshepel** [comment]
@mrleblanc101 I just added `sprite.svg` to the `.gitignore`

You're right, Vite is rewriting your [`dist` folder](https://vitejs.dev/config/build-options.html#build-outdir).

**Comment by mrleblanc101** [comment]
@vshepel I don't want to add it to my gitignore, I want it to render in the dist folder.
Maybe emit the file using Vite API instead of node directly ?

**Comment by mrleblanc101** [comment]
I changed `buildStart` hook to `buildEnd` hook and everything seems to work now.
Do you want me to open a PR ?

**Comment by mrleblanc101** [comment]
Or maybe not, the generation works.
But the file is not served by `Vite`, even thought my `index.html` and `script/index.js`  in the same folder are both served correctly.

**Comment by ShawSpring** [comment]
build asserts url has changed. 
![image](https://github.com/vshepel/vite-svg-sprite-wrapper/assets/16224265/0711e9c9-3911-4595-9cd0-1ac05e9a7e80)
to keep originals, you assert should be placed in 'public' folder, or just use the imported name
```ts
import sprite from '@/assets/sprite.svg';
console.log(sprite);
// url during development is: src/assets/sprite.svg
// url during production is: assets/sprite-FOzG8ty3.svg
```

**Comment by vshepel** [comment]
@mrleblanc101 Hi

Sorry for the delay, a new version 1.3.2 has been released, and you can do this:

```ts
export default defineConfig({
  plugins: [
    ViteSvgSpriteWrapper({
      icons: 'svg/*.svg',
      outputDir: './dist',
    }),
  ],
  build: {
    emptyOutDir: false,
  },
})
```
