### ISSUE TITLE
The sprite is not rebuilt in development mode

### ISSUE THREAD

**Issue by uskov-dev** [vshepel/vite-svg-sprite-wrapper#11]
Hello. In build mode, when the server is running, I add new files to the folder with icons or delete them from there, but the sprite is not rebuilt. The sprite is collected only when running "npm run dev" or during the build "npm run build". I am inserting the code with a picture because it is inserted crookedly.

![image](https://github.com/vshepel/vite-svg-sprite-wrapper/assets/42895871/4b92af40-46a1-4476-bdc0-33a17b48cfdc)

![image](https://github.com/vshepel/vite-svg-sprite-wrapper/assets/42895871/dbdcd6bc-797d-42e8-8446-661ea32eba06)

**Comment by vshepel** [comment]
Hi @uskov-dev. Describe the steps to start "build mode"

**Comment by uskov-dev** [comment]
https://github.com/uskov-dev/vitewrap.git

If you add or delete a file in the "src/svgsprite" folder during development mode, the sprite file will not be rebuilt. It is assembled only when the project build is launched. And one more thing, if I run the project build, the sprite file is collected in the “public” folder and I don’t have it, then an error will be displayed in the console and the file will not be collected.

**Comment by vshepel** [comment]
@uskov-dev I have added a check for outputDir if the folder doesn't exist. Please try the new version - 1.3.1 and give me feedback if everything works for you. Thanks!
