### ISSUE TITLE
emptyOutDir immediately removes the generated sprite

### ISSUE THREAD

**Issue by kinglozzer** [vshepel/vite-svg-sprite-wrapper#12]
Hi,

By default `build.emptyOutDir` is `true`, but this removes the sprite as soon as it’s generated if the `outputdir` is within `build.outDir`:

```js
import { defineConfig } from 'vite';
import ViteSvgSpriteWrapper from 'vite-svg-sprite-wrapper';

export default defineConfig({
  plugins: [
    ViteSvgSpriteWrapper({
      icons: 'src/images/icons/*.svg',
      outputDir: './dist',
    }),
  ],
  build: {
    assetsDir: '',
    emptyOutDir: true,
    copyPublicDir: false,
    manifest: true,
    outDir: './dist',
    rollupOptions: {
      input: [
        'src/js/app.js'
      ]
    },
  },
});

```

**Comment by kinglozzer** [comment]
Using `buildEnd` stops the sprite being removed, but I’m not sure if this will have other side-effects

**Comment by vshepel** [comment]
@kinglozzer Hello, could you please describe the steps to reproduce? I added your config to the example project and executed the build command - the sprite is not removed from dist...

**Comment by vshepel** [comment]
@kinglozzer I'm working on it, but the main problem is that I'm not using emitFile and transform when building, we're already having problems with that, so you can follow the progress here - https://github.com/vshepel/vite-svg-sprite-wrapper/issues/10
