### ISSUE TITLE
How can i disable adding currentColor to all svgs?

### ISSUE THREAD

**Issue by AlexanderBredun** [vshepel/vite-svg-sprite-wrapper#17]
By default currentColor added to all svgs and there is no option in settings to disable it? is it possible?

ViteSvgSpriteWrapper({
icons: './src/assets/icons/*.svg',
outputDir: './public/sprite',
sprite: { shape: {} },
})
is the answer)

**Comment by AlexanderBredun** [comment]
ViteSvgSpriteWrapper({
      icons: './src/assets/icons/*.svg',
      outputDir: './public/sprite',
      sprite: { shape: {} },
    }) 
    is the answer)

**Comment by panchakshari-pm** [comment]
This helped me. Thanks a ton!
