### ISSUE TITLE
Sprite SVG option: "mode.symbol.sprite" causes infinite loop during vite build watch

### ISSUE THREAD

**Issue by dlerm** [vshepel/vite-svg-sprite-wrapper#3]
Thanks for creating this plugin, it is really helpful to setup an svg sprite setup for my Shopify theme repo.

In configuring the plugin, I attempted to rename the outputed file to `svg-sprites.liquid` as that is the extension I need it in.

To do so, I set up the plugin like this:
```
ViteSvgSpriteWrapper({
  icons: 'src/icons/*.svg',
  outputDir: 'shopify/snippets',
  sprite: {
    mode: {
      symbol: {
        sprite: '../svg-sprites.liquid', // rename
      },
    },
    shape: { ... },
  },
});
```

After making this update, when I run `vite build --watch` from the command line, the project builds over and over in an infinite loop even though I'm not changing any of the watched files.

Do you happen to know why this might be happening? Any help is appreciated.

**Comment by vshepel** [comment]
Can't reproduce
