### ISSUE TITLE
Build task writeBundle will happen after the project has been built

### ISSUE THREAD

**Issue by McGern** [vshepel/vite-svg-sprite-wrapper#6]
First, thanks for making this wrapper. 

Not sure if this is an issue with other people, or if this is just a pattern that I have gotten wrong. 

We are not saving the sprite sheet in source control because it is a generated asset and would just cause merge conflicts (assume that's reasonably normal behaviour for most people). Our issue is that we are using that sprite file in our react app and to generate typescript types so will cause the build to fail because the file doesn't exist until the writeBundle event has happened after the build.

Is there an config option that I can set, or have some way of running it earlier in the build process?

**Comment by vshepel** [comment]
@McGern Hi! I'm not sure that I fully understood your question, but if you want to generate typescript types, you can check https://github.com/vshepel/vite-svg-sprite-wrapper/pull/8

**Comment by McGern** [comment]
Hi @vshepel.
Thanks for getting back to me. The type addition looks good, but I think it will have the same issue. 

writeBundle only happens after the code has been compiled and type checked, so if you have this scenario (which is pretty common) it won't work, at least it didn't for me
- Generated files aren't added to source control
- Deployment server downloads a fresh version of the repo which doesn't contain the generated files
- The deployment server runs "npm build" or something similar
- writeBundle happens after the build is completed meaning the generated files still don't exist
- The code is compiled and type checked
- Because the types that are being used in the solution don't exist yet, the build will fail
- writeBundle won't get hit because the build failed.

During local development, the action is happening on the buildStart but only when in "serve" mode, so it should work. And because those files have been generated already on the local machine, doing a build afterwards will work because those files exist.

**Comment by vshepel** [comment]
@McGern Check it out and let me know if it worked for you this - https://github.com/vshepel/vite-svg-sprite-wrapper/commit/f94762e1434bb0a72a26f0797525a23269551bc1

**Comment by McGern** [comment]
Thanks very much @vshepel . Will see if I can get onto it later on this week, bit ramped at the moment, but really appreciate you having a look at this.

**Comment by vshepel** [comment]
Close https://github.com/vshepel/vite-svg-sprite-wrapper/commit/f94762e1434bb0a72a26f0797525a23269551bc1
